# SITE CONFIGURATION
baseurl: ""
url: "http://persuasiveblog.com"

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Persuasive Blog
  avatar: 
  gravatar: 1426c34fb2ce4d641018dc5f8b0790b1 # Email MD5 hash
  description: "Learn to blog so persuasively you could: Launch a freedom business. Create a buzz around your products and services. Become a popular go-to authority. Start a movement. Change the course of human history. (*Ahem* well, maybe.)" # used by search engines

  # Header and footer text
  header_text: >

  header_text_feature_image:
  footer_text: >
   Copyright © 2015 Mary E. Fernandez

  # Webinar
  webinar_title: "Blogging for Business 101: How to Go From a Total Nobody to the #1 Go-To Expert in Your Field"
  webinar_date: "26"
  webinar_day: "Friday"
  webinar_month: "June"
  webinar_time: "10:00 am Pacific / 12:00 pm Central / 1:00 pm Eastern"
  webinar_start: "06/26/2015 10:00 AM"
  webinar_end: "06/26/2015 11:00 AM"
  webinar_date_format: "06/26/2015"
  webinar_benefits: >
    <ul class="benefits" id="benefits">
    <h4>Hi! I'm Mary Fernandez (a self-proclaimed blogoholic). In this free training, I'll show you:</h4>
    <li>The key reason why most blogs FAIL to bring in the dough. (Hint: it does NOT have to do with the quality or quantity of your content.)</li>
    <li>Why becoming the go-to expert in your field isn't as hard as you might think, and why you never have to be a fraud, or "fake it 'till you make it."</li>
    <li>How to discover what you are already an expert in and get paid for it, even if you have ZERO skills. Seriously.</li>
    <li>How to grow your following and your credibility at the SPEED OF LIGHT (well, something like that), on a tight budget.</li>
    <li>How to stand out in a crowded blogosphere and dominate your niche.</li>
    </ul>
  list_id: "c242d637ac"
  
  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: 
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest: "maryefernandez"
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "maryefern"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-58431978-1" # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: "persuasivebloggers"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
