# SITE CONFIGURATION
baseurl: ""
url: "http://persuasiveblog.com"

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Persuasive Blog
  avatar: 
  gravatar: 1426c34fb2ce4d641018dc5f8b0790b1 # Email MD5 hash
  description: "Learn to blog so persuasively you could: Launch a freedom business. Create a buzz around your products and services. Become a popular go-to authority. Start a movement. Change the course of human history. (*Ahem* well, maybe.)" # used by search engines

  # Header and footer text
  header_text: >

  header_text_feature_image:
  footer_text: >
   Copyright © 2015 Mary E. Fernandez

  # Webinar
  webinar_title: "How to Get Your First 500 Leads in 60 Days for the Price of a Cup of Coffee"
  webinar_date: "2"
  webinar_day: "Thursday"
  webinar_month: "July"
  webinar_time: "12:00 pm Pacific / 2:00 pm Central / 3:00 pm Eastern"
  webinar_start: "07/02/2015 12:00 PM"
  webinar_end: "07/02/2015 1:15 PM"
  webinar_date_format: "07/02/2015"
  webinar_benefits: >
    <ul class="benefits" id="benefits">
    <h4>Hi, I'm Mary Fernandez! In this free training, I'll show you:</h4>
    <li>Exactly how I grew my list from 0 to 500 leads in approx. 60 days using Facebook Ads on a tiny budget of $5 per day. (That’s the cost of a Venti Caramel Frappuccino at Starbucks!)</li>
    <li>How to create an offer that your ideal clients and customers can't resist.</li>
    <li>How to write ad copy that converts.</li>
    <li>How to create eye-catching images that attract the right people to your list.</li>
    <li>How to set up and run your ad in Facebook's Power Editor.</li>
    <li>The one simple thing you can do to potentially cut your cost per lead in HALF and grow your list even faster.</li>
    </ul>
  list_id: "c242d637ac"
  
  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: 
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest: "maryefernandez"
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "maryefern"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-58431978-1" # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: "persuasivebloggers"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
