# SITE CONFIGURATION
baseurl: ""
url: "http://persuasiveblog.com"

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Persuasive Blog
  avatar: 
  gravatar: 1426c34fb2ce4d641018dc5f8b0790b1 # Email MD5 hash
  description: "Persuasive blogging strategies made so simple that anyone can incite action. Become a thought leader. Even change the world." # used by search engines

  # Header and footer text
  header_text: >

  header_text_feature_image:
  footer_text: >
   Copyright © 2015 Mary E. Fernandez

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: 
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest: "maryefernandez"
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "maryefern"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-58431978-1" # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: "persuasivebloggers"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
